### ISSUE TITLE
2020.5 Bug

### ISSUE THREAD

**Issue by MrScautHD** [Max094Reikeb/ExtraProceduresPlugin#3]
Hi This Plugin is in 2020.5 not working Pls make a Version for it! pls

**Comment by MrScautHD** [comment]
its a really nice Plugin pls make a Update for it :)!

**Comment by Max094Reikeb** [comment]
Update for 2020.5 will not come because the 2020.5 is not out.
It's not the first time you're asking an update before a final version comes out (you already asked with 2020.4 with a bug that was fixed when the final version was out [https://github.com/Max094Reikeb/ExtraProceduresPlugin/issues/1](https://github.com/Max094Reikeb/ExtraProceduresPlugin/issues/1))

**Comment by MrScautHD** [comment]
pls klemen have say not many changes for Plugin Maker
pls give me a dev version of it.

**Comment by MrScautHD** [comment]
This have Klemen say: A warning for plugin devs. Since 2020.5, procedure blocks that cause freemarker template generation errors, will cause the whole procedure to not generate its code. This is added to reduce the cases where some procedure blocks fail to generate due to problems in plugin and then such problems are hard to detect.

**Comment by MrScautHD** [comment]
The Ep-r1.1 Version is working in 2020.5 :)

**Comment by Max094Reikeb** [comment]
The r1.1 version is outdated. I highly advise you to stay in 2020.4 and use the r1.2 version. Why is that? Because file names are different in r1.2 and this might break all your procedures when you'll move from r1.1 to r1.2 or higher.

**Comment by MrScautHD** [comment]
ok but i have downgrade it of 1.2 to 1.1 why is this than now work?
